apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 3booda24/golang-openshift:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD_FILE
          value: /app/db-password
        volumeMounts:
        - name: db-secret
          mountPath: /app
          readOnly: true
      volumes:
      - name: db-secret
        secret:
          secretName: db-secret
          items:
          - key: db-password
            path: db-password

