apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: webapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: crc-csi-hostpath-provisioner
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: kubevirt.io.hostpath-provisioner
    volumeHandle: db-pv-volume
